### GET riot profile
GET http://localhost:3000/accounts/LickWidFyre/Licky?region=americas

###

GET http://localhost:3000/players/S7rqNDzk_oRKNPslMxI9P4mmz8UevjTxGsLKTeu32rdJdtNgUMJMVJNNRic1pOQUTb6aC6boyd0ryA?platform=na1

###

GET http://localhost:3000/ping